version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/clouds
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application-restart.sh
      timeout: 300
      runas: ubuntu