version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/clouds
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
