service: lambda-iot-devices-sqs-processor-through-api
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1
functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
plugins:
  - serverless-offline

