name: Build and Deploy the Backend REST API (Nest.js + Swagger).

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List of files
        run: ls -lA

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: NPM install, build
        run: |
          npm install
          npm run build
          ls -lA

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload files to AWS S3 bucket
        run: |
          aws s3 copy --cache-control 'no-cache' dist s3://${{ secrets.AWS_S3_BUCKET }}